using System.Diagnostics;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;

namespace DevSuite.Launcher;

/// <summary>
/// No-download debugger fallback (PLAN section 6/8): one Visual Studio
/// DebugAdapterHost launch file per dotnet service, written to
/// &lt;work_dir&gt;/vs/attach-&lt;service&gt;.json. VS starts the adapter as
/// `&lt;engine&gt; exec -i &lt;container&gt; /remote_debugger/vsdbg --interpreter=vscode`,
/// i.e. it uses the vsdbg devsuite already mounted and never runs GetVsDbg.sh.
///
/// In VS: View > Other Windows > Command Window, then paste the line from
/// &lt;work_dir&gt;/vs/attach-commands.txt:
///   DebugAdapterHost.Launch /LaunchJson:"...\attach-orders-api.json" /EngineGuid:541B8A8A-6081-4506-9F0A-1CE771DEBC04
/// </summary>
internal sealed class AttachConfigGenerator(DevSuiteSettings settings)
{
    // vsdbg (coreclr) engine for DebugAdapterHost.Launch.
    public const string CoreClrEngineGuid = "541B8A8A-6081-4506-9F0A-1CE771DEBC04";

    public sealed record ServiceAttach(string Service, string Container, string File, string Reason);

    public List<ServiceAttach> Generate()
    {
        var model = ReadComposeModel();
        var outDir = Path.Combine(settings.WorkDirFull, "vs");
        Directory.CreateDirectory(outDir);
        foreach (var stale in Directory.GetFiles(outDir, "attach-*.json"))
            File.Delete(stale);

        var project = settings.ResolveProjectName();
        var engine = ToolLocator.ResolveEngine(settings.Engine);
        var written = new List<ServiceAttach>();
        if (model?["services"] is not JsonObject services)
        {
            Log.Warn("attach", "no services found in the compose model; no attach files written");
            return written;
        }

        foreach (var (name, node) in services)
        {
            if (node is not JsonObject svc)
                continue;
            var reason = DotnetReason(name, svc);
            if (reason is null)
                continue;
            var container = svc["container_name"]?.GetValue<string>() ?? $"{project}-{name}-1";
            var file = Path.Combine(outDir, $"attach-{name}.json");
            File.WriteAllText(file, BuildLaunchJson(name, container, engine, svc).ToJsonString(new JsonSerializerOptions { WriteIndented = true }));
            written.Add(new ServiceAttach(name, container, file, reason));
            Log.Info("attach", $"{name}: {Path.GetRelativePath(settings.Root, file)} (container {container}, {reason})");
        }

        var commands = new StringBuilder();
        commands.AppendLine("# Visual Studio: View > Other Windows > Command Window, paste one line (container must be running).");
        commands.AppendLine("# Generated by DevSuite.Launcher (attach-config); regenerated on every `up`.");
        foreach (var w in written)
            commands.AppendLine($"DebugAdapterHost.Launch /LaunchJson:\"{w.File}\" /EngineGuid:{CoreClrEngineGuid}");
        File.WriteAllText(Path.Combine(outDir, "attach-commands.txt"), commands.ToString());
        if (written.Count == 0)
            Log.Info("attach", "no dotnet services with the debugger enabled; no attach files written");
        return written;
    }

    /// <summary>Why the service is a debuggable dotnet service, or null to skip it.</summary>
    private string? DotnetReason(string name, JsonObject svc)
    {
        if (svc["build"] is null)
            return null;
        var labels = Labels(svc);
        if (labels.TryGetValue("tilt-debugger", out var dbg) && dbg.Trim().Equals("false", StringComparison.OrdinalIgnoreCase))
        {
            Log.Debug("attach", $"{name}: tilt-debugger=false, skipped");
            return null;
        }
        if (labels.TryGetValue("tilt-build", out var kind))
            return kind.Trim() == "dotnet" ? "tilt-build=dotnet" : null;
        if (settings.DefaultBuildKind != "dotnet")
            return null;
        // Defaulted kind: dotnet.star falls back to `docker` without exactly one
        // csproj next to the Dockerfile, so only claim it when that holds.
        if (labels.ContainsKey("tilt-project"))
            return "default kind, tilt-project set";
        var dockerDir = DockerfileDir(svc);
        if (dockerDir is not null && Directory.Exists(dockerDir) && Directory.GetFiles(dockerDir, "*.csproj").Length == 1)
            return "default kind, one csproj";
        Log.Debug("attach", $"{name}: no tilt-build label and not exactly one csproj next to the Dockerfile, skipped");
        return null;
    }

    private JsonObject BuildLaunchJson(string service, string container, string engine, JsonObject svc)
    {
        var config = new JsonObject
        {
            ["name"] = $"Attach {service} (vsdbg in container {container})",
            ["type"] = "coreclr",
            ["request"] = "attach",
            ["processName"] = settings.AttachProcessName,
            ["$adapter"] = engine,
            ["$adapterArgs"] = $"exec -i {container} {settings.DebuggerPath} --interpreter=vscode",
            ["justMyCode"] = true,
        };
        // Full in-container builds compile under /src (MS Dockerfile template):
        // map it back to the build context so breakpoints bind. Local publishes
        // (skip build layer) already carry local paths in their pdbs.
        var context = BuildContext(svc);
        if (context is not null)
            config["sourceFileMap"] = new JsonObject { ["/src/"] = EnsureTrailingSeparator(context) };
        return config;
    }

    private static Dictionary<string, string> Labels(JsonObject svc)
    {
        var result = new Dictionary<string, string>();
        switch (svc["labels"])
        {
            case JsonObject dict:
                foreach (var (k, v) in dict)
                    result[k] = v?.ToString() ?? "";
                break;
            case JsonArray list:
                foreach (var item in list)
                {
                    var s = item?.ToString() ?? "";
                    var eq = s.IndexOf('=');
                    if (eq > 0)
                        result[s[..eq]] = s[(eq + 1)..];
                    else if (s.Length > 0)
                        result[s] = "";
                }
                break;
        }
        return result;
    }

    private string? BuildContext(JsonObject svc)
    {
        var context = svc["build"] switch
        {
            JsonValue v => v.GetValue<string>(),
            JsonObject b => b["context"]?.GetValue<string>() ?? ".",
            _ => null,
        };
        return context is null ? null : Path.GetFullPath(context, ComposeDir);
    }

    private string? DockerfileDir(JsonObject svc)
    {
        var context = BuildContext(svc);
        if (context is null)
            return null;
        var dockerfile = (svc["build"] as JsonObject)?["dockerfile"]?.GetValue<string>() ?? "Dockerfile";
        return Path.GetDirectoryName(Path.GetFullPath(dockerfile, context));
    }

    private string ComposeDir =>
        Path.GetDirectoryName(Path.GetFullPath(settings.ComposeFiles.FirstOrDefault() ?? "docker-compose.yml", settings.Root))!;

    private static string EnsureTrailingSeparator(string path) =>
        path.EndsWith(Path.DirectorySeparatorChar) ? path : path + Path.DirectorySeparatorChar;

    /// <summary>
    /// `&lt;compose_cmd&gt; -f ... config --format json`: the normalized model
    /// (interpolation, multiple files, list/dict labels all resolved).
    /// </summary>
    private JsonNode? ReadComposeModel()
    {
        var parts = settings.ComposeCmd.Split(' ', StringSplitOptions.RemoveEmptyEntries);
        if (parts.Length == 0)
            return null;
        var psi = new ProcessStartInfo(parts[0])
        {
            WorkingDirectory = settings.Root,
            UseShellExecute = false,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
        };
        foreach (var p in parts.Skip(1))
            psi.ArgumentList.Add(p);
        psi.ArgumentList.Add("-p");
        psi.ArgumentList.Add(settings.ResolveProjectName());
        foreach (var f in settings.ComposeFiles)
        {
            psi.ArgumentList.Add("-f");
            psi.ArgumentList.Add(Path.GetFullPath(f, settings.Root));
        }
        psi.ArgumentList.Add("config");
        psi.ArgumentList.Add("--format");
        psi.ArgumentList.Add("json");
        Log.Debug("attach", $"> {settings.ComposeCmd} {string.Join(' ', psi.ArgumentList.Skip(parts.Length - 1))}");

        try
        {
            using var p = Process.Start(psi)!;
            var stderr = p.StandardError.ReadToEndAsync();
            var stdout = p.StandardOutput.ReadToEnd();
            p.WaitForExit();
            if (p.ExitCode != 0)
            {
                Log.Warn("attach", $"'{settings.ComposeCmd} config' failed ({p.ExitCode}): {stderr.Result.Trim()}");
                return null;
            }
            return JsonNode.Parse(stdout);
        }
        catch (System.ComponentModel.Win32Exception e)
        {
            Log.Warn("attach", $"cannot run '{settings.ComposeCmd}' ({e.Message}); set compose_cmd in devsuite.json");
            return null;
        }
    }
}
